# language mapping
languages_mappping = {
    "English":      {"iso2": "en", "iso3": "eng"},
    "German":       {"iso2": "de", "iso3": "ger"},
    "Turkish":      {"iso2": "tr", "iso3": "tur"},
    "Arabic":       {"iso2": "ar", "iso3": "arb"},
    "Bengali":      {"iso2": "bn", "iso3": "ben"},
    "Bulgarian":    {"iso2": "bg", "iso3": "bul"},
    "Chinese":      {"iso2": "zh", "iso3": "chn"},
    "Croatian":     {"iso2": "hr", "iso3": "hrv"},
    "Czech":        {"iso2": "cs", "iso3": "czh"},
    "Finnish":      {"iso2": "fi", "iso3": "fin"},
    "French":       {"iso2": "fr", "iso3": "fra"},
    "Greek":        {"iso2": "el", "iso3": "grk"},
    "Hebrew":       {"iso2": "he", "iso3": "heb"},
    "Hindi":        {"iso2": "hi", "iso3": "hin"},
    "Hungarian":    {"iso2": "hu", "iso3": "hun"},
    "Italian":      {"iso2": "it", "iso3": "ita"},
    "Japanese":     {"iso2": "ja", "iso3": "jpn"},
    "Korean":       {"iso2": "ko", "iso3": "kor"},
    "Norwegian":    {"iso2": "no", "iso3": "nor"},
    "Polish":       {"iso2": "pl", "iso3": "pol"},
    "Portuguese":   {"iso2": "pt", "iso3": "por"},
    "Romanian":     {"iso2": "ro", "iso3": "rom"},
    "Russian":      {"iso2": "ru", "iso3": "rus"},
    "Serbian":      {"iso2": "sr", "iso3": "srb"},
    "Slovak":       {"iso2": "sk", "iso3": "svk"},
    "Spanish":      {"iso2": "es", "iso3": "spa"},
    "Swedish":      {"iso2": "sv", "iso3": "swe"},
    "Ukrainian":    {"iso2": "uk", "iso3": "ukr"},
    "Vietnamese":   {"iso2": "vi", "iso3": "vie"}
}